### ISSUE TITLE
4.0 release plan

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#742]
This is the current plan for 4.0 release:
- [ ] deprecate APIs which are included in JupyterLab's 4.0 `@jupyterlab/lsp` package
   - [ ] try to harmonise them to minimise the cost of switchover once lab 4.0 is released
   - [ ] remove previously deprecated methods
- [x] move plugins to `@jupyter-lsp` namespace
- [ ] turn on more eslint rules, including camelCase #47
- [x] refactor jump-to function to suport jumping to references (https://github.com/jupyter-lsp/jupyterlab-lsp/pull/739)
   - [ ] modal
- [ ] split up features into packages https://github.com/jupyter-lsp/jupyterlab-lsp/issues/76
- [ ] add a scaffold for new features:
   - [ ] symbol navigation (sidebar panel, + modal) https://github.com/jupyter-lsp/jupyterlab-lsp/issues/43
   - [ ] code actions and commands (#676)
- [ ] typdoc documentation

If time permits:
- [ ] multiple language servers per document (will close https://github.com/jupyter-lsp/jupyterlab-lsp/issues/437)
- [ ] https://github.com/jupyter-lsp/jupyterlab-lsp/issues/681

**Comment by bollwyvl** [comment]
These are very good goals, thank you for picking up this part of the planning!  I'll see how much time i can put towards assisting. 

Regarding timeline/upstreams: are we thinking this will target `jupyterlab 3` and `retrolab`, or should we be shooting more for `lab4`/`notebook7`?

If we _do_ go after #437, I think we want to make sure it covers as much of #184 as we can. A win from that would be at least _some_ js-based language servers running inside the browser. While this would need to work _outside_ of jupyterlite. This would improve our demo capability (see binder issues on #724) and, for things like the JSON/YAML language servers, substantially improve our ability to deliver just-in-time features, shipped only in the browser, and without nodejs.

**Comment by krassowski** [comment]
> Regarding timeline/upstreams: are we thinking this will target jupyterlab 3 and retrolab, or should we be shooting more for lab4/notebook7?

I would currently aim to release it with 3.3, but if it is not ready before Lab4 release then I guess it makes sense to add support for Lab4 too.

I was reading through #184 yesterday and I agree that these issues should be considered together. My first thought was that I would not want to land #184 before #437, so added #437 as a more realistic (time-wise) goal.
