### ISSUE TITLE
5.1 release plan

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#985]
Wishlist:
- [ ] add new features:
   - [ ] symbol navigation (sidebar panel, + modal) https://github.com/jupyter-lsp/jupyterlab-lsp/issues/43 - it may go directly upstream
   - [ ] formatting
   - [ ] code actions and commands (#676)
- [ ] typdoc documentation
- [ ] deprecate `.lsp-symlink` and prefer DAP `source` request (we cannot drop it as most kernels do not support DAP), reusing https://github.com/jupyterlab/jupyterlab/pull/13390)
- [ ] multiple language servers per document (will close https://github.com/jupyter-lsp/jupyterlab-lsp/issues/437)
- [ ] https://github.com/jupyter-lsp/jupyterlab-lsp/issues/681
