### ISSUE TITLE
Tests which need work after 5.0 release

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#997]
- Integration tests skipped due to known upstream issues:
   - [ ] `Invalidates On Focus Loss` - upstream issue https://github.com/jupyterlab/jupyterlab/issues/14496
   - [ ] `Docker` rename - upstream issue (https://github.com/jupyterlab/jupyterlab/issues/15104)
   - [ ] `Robot` mode - upstream issue (https://github.com/MarketSquare/jupyterlab_robotmode/issues/14)
   - [ ] `Mid Token Completions Do Not Overwrite` - looks like a bug in the upstream reconciliator, no upstream issue yet but it basically requires changes on JEP level to make kernels return proper ranges rather than randomly either return completion with or without suffix
- Integration tests skipped as passing locally (help wanted):
   - [ ] `Columns Can Be Hidden` - passes locally; also tested in Firefox and Chrome works ok
   - [ ] `Hover works in foreign code (javascript)` - passes locally but flaky
   - [ ] `Diagnostics Panel Works After Removing Foreign Document` - passes locally
- Other problems
   - [ ] `Python Dotted` this highlights a genuine problem with dotted settings, now documented.
   - [ ] `Highlighting Mode Changes Back And Forth After Edits` - this is likely to 2.5 seconds delay workaround (which can only be fixed once JupyterLab 4.1 is out)
